# FEATURE EXTRACTION
fs: 22050
hop_length: 315
n_fft: 1024
n_mel: 80
# snippet_length_sec: 5
min_clip: 0.0000001
fmin: 27.5
fmax: 8000
max_song_length: 625
# NETWORK
learning_rate: 0.001
epochs: 3
num_train_steps: 1250
songs_to_validate: 3
batch_size: 32
sample_frame_length: 115
final_activation: 'sigmoid'